# Travis is now container based which doesn't support sudo
sudo: false
language: csharp
solution: RubberStamp.sln
 
install:
  - nuget restore RubberStamp.sln
  - nuget install NUnit.Console -Version 3.0.1 -OutputDirectory testrunner
 
script:
  - xbuild /p:Configuration=Release RubberStamp.sln
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe ./src/Tests/RubberStamp.UnitTest/bin/Release/RubberStamp.UnitTest.dll